final List<Map<String, dynamic>> regionData = [
  {'name': 'Hà Nội', 'value': 3},
  {'name': 'Quảng Ninh', 'value': 0},
  {'name': 'Bắc Ninh', 'value': 0},
  {'name': 'Cao Bằng', 'value': 0},
  {'name': 'Hưng Yên', 'value': 0},
  {'name': 'Lào Cai', 'value': 0},
  {'name': 'Thái Nguyên', 'value': 0},
  {'name': 'Ninh Bình', 'value': 0},
  {'name': 'Phú Thọ', 'value': 0},
  {'name': 'Hải Phòng', 'value': 0},
  {'name': 'Tuyên Quang', 'value': 0},
  {'name': 'Lai Châu', 'value': 0},
  {'name': 'Lạng Sơn', 'value': 0},
  {'name': 'Sơn La', 'value': 0},
  {'name': 'Điện Biên', 'value': 0},
  {'name': 'Thanh Hóa', 'value': 1},
  {'name': 'Nghệ An', 'value': 1},
  {'name': 'Hà Tĩnh', 'value': 1},
  {'name': 'Quảng Trị', 'value': 1},
  {'name': 'Thừa Thiên Huế', 'value': 1},
  {'name': 'Đà Nẵng', 'value': 1},
  {'name': 'Quảng Ngãi', 'value': 1},
  {'name': 'Gia Lai', 'value': 1},
  {'name': 'Đắk Lắk', 'value': 1},
  {'name': 'Lâm Đồng', 'value': 1},
  {'name': 'Khánh Hòa', 'value': 1},
  {'name': 'Hoàng Sa (Đà Nẵng)', 'value': 1},
  {'name': 'Trường Sa (Khánh Hòa)', 'value': 1},
  {'name': 'TP Hồ Chí Minh', 'value': 2},
  {'name': 'Tây Ninh', 'value': 2},
  {'name': 'Đồng Nai', 'value': 2},
  {'name': 'Vĩnh Long', 'value': 2},
  {'name': 'An Giang', 'value': 2},
  {'name': 'Đồng Tháp', 'value': 2},
  {'name': 'Cần Thơ', 'value': 2},
  {'name': 'Cà Mau', 'value': 2},
];