final List<Map<String, dynamic>> regionData = [
  {'name': 'Hà Nội', 'value': 3},
  {'name': 'Quảng Ninh', 'value': 0},
  {'name': 'Bắc Ninh', 'value': 0},
  {'name': 'Cao Bằng', 'value': 0},
  {'name': 'Hưng Yên', 'value': 0},
  {'name': 'Lào Cai', 'value': 0},
  {'name': 'Thái Nguyên', 'value': 0},
  {'name': 'Ninh Bình', 'value': 0},
  {'name': 'Phú Thọ', 'value': 0},
  {'name': 'Hải Phòng', 'value': 0},
  {'name': 'Tuyên Quang', 'value': 0},
  {'name': 'Lai Châu', 'value': 0},
  {'name': 'Lạng Sơn', 'value': 0},
  {'name': 'Sơn La', 'value': 0},
  {'name': 'Điện Biên', 'value': 0},
  {'name': 'Thanh Hóa', 'value': 1},
  {'name': 'Nghệ An', 'value': 1},
  {'name': 'Hà Tĩnh', 'value': 1},
  {'name': 'Quảng Trị', 'value': 1},
  {'name': 'Thừa Thiên Huế', 'value': 1},
  {'name': 'Đà Nẵng', 'value': 1},
  {'name': 'Quảng Ngãi', 'value': 1},
  {'name': 'Gia Lai', 'value': 1},
  {'name': 'Đắk Lắk', 'value': 1},
  {'name': 'Lâm Đồng', 'value': 1},
  {'name': 'Khánh Hòa', 'value': 1},
  {'name': 'Hoàng Sa (Đà Nẵng)', 'value': 1},
  {'name': 'Trường Sa (Khánh Hòa)', 'value': 1},
  {'name': 'TP Hồ Chí Minh', 'value': 2},
  {'name': 'Tây Ninh', 'value': 2},
  {'name': 'Đồng Nai', 'value': 2},
  {'name': 'Vĩnh Long', 'value': 2},
  {'name': 'An Giang', 'value': 2},
  {'name': 'Đồng Tháp', 'value': 2},
  {'name': 'Cần Thơ', 'value': 2},
  {'name': 'Cà Mau', 'value': 2},
];

final List<Map<String, dynamic>> densityData = [
  {'name': 'Hà Nội', 'value': 1850},
  {'name': 'TP. Hồ Chí Minh', 'value': 2100},
  {'name': 'Hải Phòng', 'value': 1200},
  {'name': 'Đà Nẵng', 'value': 1350},
  {'name': 'Cần Thơ', 'value': 950},
  {'name': 'Hà Giang', 'value': 300},
  {'name': 'Cao Bằng', 'value': 280},
  {'name': 'Bắc Kạn', 'value': 250},
  {'name': 'Tuyên Quang', 'value': 400},
  {'name': 'Lào Cai', 'value': 450},
  {'name': 'Điện Biên', 'value': 220},
  {'name': 'Lai Châu', 'value': 200},
  {'name': 'Sơn La', 'value': 380},
  {'name': 'Yên Bái', 'value': 420},
  {'name': 'Hoà Bình', 'value': 500},
  {'name': 'Thái Nguyên', 'value': 850},
  {'name': 'Lạng Sơn', 'value': 480},
  {'name': 'Quảng Ninh', 'value': 1400},
  {'name': 'Bắc Giang', 'value': 900},
  {'name': 'Phú Thọ', 'value': 750},
  {'name': 'Vĩnh Phúc', 'value': 1100},
  {'name': 'Bắc Ninh', 'value': 1550},
  {'name': 'Hải Dương', 'value': 1050},
  {'name': 'Hưng Yên', 'value': 1000},
  {'name': 'Thái Bình', 'value': 950},
  {'name': 'Hà Nam', 'value': 800},
  {'name': 'Nam Định', 'value': 880},
  {'name': 'Ninh Bình', 'value': 720},
  {'name': 'Thanh Hoá', 'value': 980},
  {'name': 'Nghệ An', 'value': 920},
  {'name': 'Hà Tĩnh', 'value': 600},
  {'name': 'Quảng Bình', 'value': 550},
  {'name': 'Quảng Trị', 'value': 480},
  {'name': 'Thừa Thiên Huế', 'value': 820},
  {'name': 'Quảng Nam', 'value': 700},
  {'name': 'Quảng Ngãi', 'value': 650},
  {'name': 'Bình Định', 'value': 780},
  {'name': 'Phú Yên', 'value': 520},
  {'name': 'Khánh Hoà', 'value': 1150},
  {'name': 'Ninh Thuận', 'value': 450},
  {'name': 'Bình Thuận', 'value': 700},
  {'name': 'Kon Tum', 'value': 320},
  {'name': 'Gia Lai', 'value': 480},
  {'name': 'Đắk Lắk', 'value': 620},
  {'name': 'Đắk Nông', 'value': 350},
  {'name': 'Lâm Đồng', 'value': 900},
  {'name': 'Bình Phước', 'value': 580},
  {'name': 'Tây Ninh', 'value': 720},
  {'name': 'Bình Dương', 'value': 1800},
  {'name': 'Đồng Nai', 'value': 1700},
  {'name': 'Bà Rịa - Vũng Tàu', 'value': 1450},
  {'name': 'Long An', 'value': 850},
  {'name': 'Tiền Giang', 'value': 800},
  {'name': 'Bến Tre', 'value': 650},
  {'name': 'Trà Vinh', 'value': 500},
  {'name': 'Vĩnh Long', 'value': 680},
  {'name': 'Đồng Tháp', 'value': 750},
  {'name': 'An Giang', 'value': 820},
  {'name': 'Kiên Giang', 'value': 900},
  {'name': 'Hậu Giang', 'value': 480},
  {'name': 'Sóc Trăng', 'value': 550},
  {'name': 'Bạc Liêu', 'value': 520},
  {'name': 'Cà Mau', 'value': 600},
];
